@startuml

class InventoryItemsApp  {
    public  start()
    }
class InventoryItemsController {

}
class InventoryItem{
    - itemValue : SimpleStringProperty
    - temSerialNumber : SimpleStringProperty
    - itemName: SimpleStringProperty
    + InventoryItem()
    + getItemValue()
    + itemValueProperty()
    + getItemsSerialNumber()
    + itemSerialNumberProperty()
    + setItemsSerialNumber(String itemsSerialNumber)
    + getItemName()
    + setItemName()
    + setItemName()
}
class ItemInventoryManager {

}
@enduml